language: python

before_install:
 - chmod +x ./st.sh

install:
 - pip3 install flask
 - pip3 install gunicorn
 - pip3 install requests
 - pip3 install pytest
 - pip3 install codecov

script:
 - ./st.sh

after_success:
 - codecov
